In [170]:
import pandas as pd

df = pd.read_excel('residuos_final.xlsx', sheet_name='2019')
df1 = pd.read_excel('residuos_final.xlsx', sheet_name='2020')
df2 = pd.read_excel('residuos_final.xlsx', sheet_name='2021')
df2

                          Tipo de resíduo - Toneladas  Janeiro  Fevereiro
0                                          DOMICILIAR   308771     278866
1                                  ENTULHO MECANIZADO     7807       7117
2                                RESIDUOS DE ECOPONTO    28024      27865
3                                            DIVERSOS    27866      24265
4                                              ESGOTO    16607      16613
5                                RESIDUOS DE PISCINAO    16395      18258
6                                RESIDUOS DE CORREGOS    22680      20375
7                                            VARRICAO     5298       6944
8                                            SELETIVA     7651       6647
9                                         FEIRA LIVRE     6303       5874
10                                     ENTULHO MANUAL     1127       1122
11                                               PODA     6102       5836
12                                           GG SAUDE     3370       3334
13                                    REJEITO-CMT CMJ     1648       1276
14                           RESIDUOS DE BOCA DE LOBO     1468       1794
15                                           PG SAUDE      753        813
16                       REMOCAO RESIDUOS DESCARTADOS        0          0
17                         RESIDUOS PATIO COMPOSTAGEM        0          0
18                                            REJEITO        0          0
19                                 ENTULHO APREENDIDO        0          0
20                                            MADEIRA     5808       5582
21                                            ANIMAIS        1          2
22                                VARRICAO MECANIZADA      374        499
23                                      ALIM VENCIDOS        0          0
24                               RESIDUO DE APREENSAO      240        247
25                              RESIDUO DE ACUMULADOR       30         93
26                            RESIDUO DE DESFAZIMENTO       54        253
27  EQUIPE DE EVENTOS ESPECIAIS E OPERACOES DE EME...        0          0
28                         RESIDUO ECOPONTO - ENTULHO     4074       5825
29                                  ENTULHO DO PREDIO        0          0
30                                     LIMPEZA URBANA        0          0
31                    RESIDUOS DE ECOPONTO - DIVERSOS      268        304
32                                        Total geral   472719     439805

In [171]:
df2

                          Tipo de resíduo - Toneladas  Janeiro  Fevereiro
0                                          DOMICILIAR   308771     278866
1                                  ENTULHO MECANIZADO     7807       7117
2                                RESIDUOS DE ECOPONTO    28024      27865
3                                            DIVERSOS    27866      24265
4                                              ESGOTO    16607      16613
5                                RESIDUOS DE PISCINAO    16395      18258
6                                RESIDUOS DE CORREGOS    22680      20375
7                                            VARRICAO     5298       6944
8                                            SELETIVA     7651       6647
9                                         FEIRA LIVRE     6303       5874
10                                     ENTULHO MANUAL     1127       1122
11                                               PODA     6102       5836
12                                           GG SAUDE     3370       3334
13                                    REJEITO-CMT CMJ     1648       1276
14                           RESIDUOS DE BOCA DE LOBO     1468       1794
15                                           PG SAUDE      753        813
16                       REMOCAO RESIDUOS DESCARTADOS        0          0
17                         RESIDUOS PATIO COMPOSTAGEM        0          0
18                                            REJEITO        0          0
19                                 ENTULHO APREENDIDO        0          0
20                                            MADEIRA     5808       5582
21                                            ANIMAIS        1          2
22                                VARRICAO MECANIZADA      374        499
23                                      ALIM VENCIDOS        0          0
24                               RESIDUO DE APREENSAO      240        247
25                              RESIDUO DE ACUMULADOR       30         93
26                            RESIDUO DE DESFAZIMENTO       54        253
27  EQUIPE DE EVENTOS ESPECIAIS E OPERACOES DE EME...        0          0
28                         RESIDUO ECOPONTO - ENTULHO     4074       5825
29                                  ENTULHO DO PREDIO        0          0
30                                     LIMPEZA URBANA        0          0
31                    RESIDUOS DE ECOPONTO - DIVERSOS      268        304
32                                        Total geral   472719     439805

In [172]:
df.drop(index=28, inplace=True)
df.drop(['Total 2019'], axis=1, inplace=True)

df1.drop(index=32, inplace=True)
df1.drop(['Total 2020'], axis=1, inplace=True)

df2.drop(index=32, inplace=True)

In [173]:
dict = {
    'tipo': [],
    'quantidade': [],
    'mes': [],
    'ano': []
}

In [174]:
meses = ['Janeiro',	'Fevereiro','Março','Abril'	,'Maio'	,'Junho','Julho'	,'Agosto',	'Setembro',	'Outubro'	,'Novembro',	'Dezembro']

index = 0

for mes in meses:
    for row in df[mes]:
        dict['tipo'].append(df['Tipo de resíduo - Toneladas'][index])
        dict['quantidade'].append(row)
        dict['ano'].append(2019)
        dict['mes'].append(mes)
        index += 1
    index = 0

In [175]:
meses = ['Janeiro',	'Fevereiro','Março','Abril'	,'Maio'	,'Junho','Julho'	,'Agosto',	'Setembro',	'Outubro'	,'Novembro',	'Dezembro']

index = 0

for mes in meses:
    for row in df1[mes]:
        dict['tipo'].append(df1['Tipo de resíduo - Toneladas'][index])
        dict['quantidade'].append(row)
        dict['ano'].append(2020)
        dict['mes'].append(mes)
        index += 1
    index = 0

In [176]:
meses = ['Janeiro',	'Fevereiro']

index = 0

for mes in meses:
    for row in df2[mes]:
        dict['tipo'].append(df2['Tipo de resíduo - Toneladas'][index])
        dict['quantidade'].append(row)
        dict['ano'].append(2021)
        dict['mes'].append(mes)
        index += 1
    index = 0

In [177]:
df_unificado = pd.DataFrame(dict)
df_unificado

,tipo,quantidade,mes,ano
0,DOMICILIAR,326387.0,Janeiro,2019
1,ENTULHO MECANIZADO,24343.0,Janeiro,2019
2,RESIDUOS DE ECOPONTO,36532.0,Janeiro,2019
3,DIVERSOS,17128.0,Janeiro,2019
4,ESGOTO,7217.0,Janeiro,2019
...,...,...,...,...
779,EQUIPE DE EVENTOS ESPECIAIS E OPERACOES DE EME...,0.0,Fevereiro,2021
780,RESIDUO ECOPONTO - ENTULHO,5825.0,Fevereiro,2021
781,ENTULHO DO PREDIO,0.0,Fevereiro,2021
782,LIMPEZA URBANA,0.0,Fevereiro,2021
783,RESIDUOS DE ECOPONTO - DIVERSOS,304.0,Fevereiro,2021

In [178]:
df_unificado.to_excel('residuos_unificado.xlsx', index=False)